# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:27
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170723_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images'),
        ),
    ]
