# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170723_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
