# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:29
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170723_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
