# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170723_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='uploaded_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
