# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:31
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170723_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
