# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='file',
        ),
    ]
