# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170729_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
