# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_photo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
