# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:53
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170805_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book1',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='book2',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
