# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:52
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170805_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file1',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
