# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file1',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
