# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 08:26
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170806_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file1',
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
