# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170806_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookgenre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookurl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
