# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20170810_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='hello', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='/static/img/face-0.jpg', upload_to='uploaded_images'),
        ),
    ]
