# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:06
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20170810_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='uploaded_images/DSC_0239.JPG', upload_to='uploaded_images'),
        ),
    ]
